// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Models;

namespace Persistence.Migrations
{
    [DbContext(typeof(BazaContext))]
    partial class BazaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FonogramIzvodjac", b =>
                {
                    b.Property<int>("FonogramId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IzvodjacId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FonogramId", "IzvodjacId");

                    b.HasIndex("IzvodjacId");

                    b.ToTable("FonogramIzvodjac");
                });

            modelBuilder.Entity("Persistence.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KataloskiBroj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumId");

                    b.ToTable("Albumi");
                });

            modelBuilder.Entity("Persistence.Models.Fonogram", b =>
                {
                    b.Property<int>("FonogramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbumId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodinaIzdanja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KataloskiBroj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .HasColumnType("TEXT");

                    b.HasKey("FonogramId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Fonogrami");
                });

            modelBuilder.Entity("Persistence.Models.Izvodjac", b =>
                {
                    b.Property<int>("IzvodjacId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .HasColumnType("TEXT");

                    b.HasKey("IzvodjacId");

                    b.ToTable("Izvodjaci");
                });

            modelBuilder.Entity("FonogramIzvodjac", b =>
                {
                    b.HasOne("Persistence.Models.Fonogram", null)
                        .WithMany()
                        .HasForeignKey("FonogramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.Models.Izvodjac", null)
                        .WithMany()
                        .HasForeignKey("IzvodjacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Models.Fonogram", b =>
                {
                    b.HasOne("Persistence.Models.Album", "Album")
                        .WithMany("Fonogrami")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Persistence.Models.Album", b =>
                {
                    b.Navigation("Fonogrami");
                });
#pragma warning restore 612, 618
        }
    }
}
